export const DEFAULT_LIMIT = 12;

export const allowedQueryKeys = [
    'page',
    'limit',
    'offset',
    'search',
    'ordering',
    'brand_id',
    'brand_in',
    'category_id',
    'category_in',
    'category_tree_id',
    'regular_price_min',
    'regular_price_max',
    'sale_price_min',
    'sale_price_max',
    'has_discount',
    'discount_percent_min',
    'discount_percent_max',
    'discount_min',
    'discount_max',
    'price_min',
    'price_max',
    'in_stock',
    'has_image',
    'has_comments',
    'comments_count_min',
    'comments_count_max',
    'rating_min',
    'rating_max',
    'id_min',
    'id_max',
    'created_date',
    'updated_date',
    'created_from',
    'created_to',
    'updated_from',
    'updated_to',
] as const;
